BEGIN;

CREATE TABLE IF NOT EXISTS menu (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	key VARCHAR(100) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scenario (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	menu_id BIGINT NOT NULL REFERENCES menu (id) ON DELETE CASCADE,
	key VARCHAR(100) NOT NULL,
	name VARCHAR(255) NOT NULL,
	display_order INTEGER NOT NULL DEFAULT 0,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT scenario_menu_key_unique UNIQUE (menu_id, key),
	CONSTRAINT scenario_menu_name_unique UNIQUE (menu_id, name)
);

CREATE TABLE IF NOT EXISTS branch (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	scenario_id BIGINT NOT NULL REFERENCES scenario (id) ON DELETE CASCADE,
	key VARCHAR(100) NOT NULL,
	name VARCHAR(255) NOT NULL,
	display_order INTEGER NOT NULL DEFAULT 0,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT branch_scenario_key_unique UNIQUE (scenario_id, key),
	CONSTRAINT branch_scenario_name_unique UNIQUE (scenario_id, name)
);

CREATE TABLE IF NOT EXISTS option (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	branch_id BIGINT NOT NULL REFERENCES branch (id) ON DELETE CASCADE,
	key VARCHAR(100) NOT NULL,
	name VARCHAR(255) NOT NULL,
	display_order INTEGER NOT NULL DEFAULT 0,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT option_branch_key_unique UNIQUE (branch_id, key),
	CONSTRAINT option_branch_name_unique UNIQUE (branch_id, name)
);

COMMIT;

